# Generated by Django 3.0.6 on 2020-08-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phone_field.models.PhoneField(blank=True, max_length=31, unique=True, verbose_name='Номер телефона')),
                ('number_of_user', models.IntegerField(default=0, verbose_name='Номер пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moduser',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=400, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость услуги')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=400, verbose_name='review')),
                ('mark', models.IntegerField(verbose_name='mark')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Дополнительная информация')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время оформление записи')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('seen', models.BooleanField(default=False, verbose_name='Просмотрено врачём')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ModificatedUser', to_field='number')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'records',
            },
        ),
    ]
