# Generated by Django 3.0.6 on 2020-08-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200818_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modificateduser',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
    ]
