# Generated by Django 3.0.6 on 2020-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doctorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_de',
            field=models.CharField(default='-', max_length=400, verbose_name='Описание на немецком'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги на немецом'),
            preserve_default=False,
        ),
    ]
