# Generated by Django 3.0.6 on 2020-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='about_text_de',
            field=models.TextField(default=1, max_length=1000, verbose_name='Про доктора на немецком'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='-', max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_de',
            field=models.TextField(default='-', max_length=400, verbose_name='Описание на немецком'),
        ),
    ]
