# Generated by Django 3.0.6 on 2020-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200830_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='about_text_de',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Про доктора на немецком'),
        ),
    ]
