# Generated by Django 3.1 on 2020-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200830_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_image', models.ImageField(null=True, upload_to='visitimages/', verbose_name='Лендинг изображения')),
            ],
            options={
                'verbose_name': 'Лендинг изображение',
                'verbose_name_plural': 'Лендинг изображения',
                'db_table': 'visitimg',
            },
        ),
    ]
