# Generated by Django 3.1 on 2020-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200904_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLoginSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google', models.BooleanField(default=True, verbose_name='Статус Google авторизации')),
                ('facebook', models.BooleanField(default=True, verbose_name='Статус FaceBook авторизации')),
            ],
            options={
                'verbose_name': 'Настройки авторизации через соц.сети',
                'db_table': 'social_auth',
            },
        ),
    ]
