# Generated by Django 3.1 on 2020-09-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_socialloginsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialloginsettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialloginsettings',
            name='google',
        ),
        migrations.AddField(
            model_name='socialloginsettings',
            name='service',
            field=models.CharField(default=1, max_length=20, verbose_name='Сервисы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialloginsettings',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус активации'),
        ),
    ]
