# Generated by Django 3.1 on 2020-10-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200927_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialloginsettings',
            options={'verbose_name': 'Настройки авторизации через соц.сети', 'verbose_name_plural': 'Настройки авторизации через соц.сети'},
        ),
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='Уточните у массажиста', max_length=100, verbose_name='Стоимость услуги'),
        ),
    ]
