# Generated by Django 3.1 on 2020-10-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201007_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость услуги'),
        ),
    ]
