# Generated by Django 3.1 on 2020-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201007_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[(1, 'Back'), (2, 'Head'), (3, 'Foot')], default=1, max_length=20, verbose_name='Категория услуги'),
            preserve_default=False,
        ),
    ]
