# Generated by Django 3.1 on 2020-10-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201012_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Массаж спины', 'Массаж спины'), ('Массаж головы', 'Массаж головы'), ('Массаж ног', 'Массаж ног')], max_length=20, verbose_name='Категория услуги'),
        ),
    ]
