# Generated by Django 3.1 on 2020-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201012_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificateduser',
            name='number_of_made_records',
            field=models.IntegerField(default=0, verbose_name='Количество сделаних записей'),
        ),
        migrations.AddField(
            model_name='modificateduser',
            name='number_of_visites',
            field=models.IntegerField(default=0, verbose_name='Количество визитов пользователя'),
        ),
    ]
