# Generated by Django 3.1 on 2020-10-30 14:14

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201020_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificateduser',
            name='number',
            field=phone_field.models.PhoneField(blank=True, default=0, max_length=31, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
